# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hgroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='17套', max_length=254, verbose_name='环境')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipaddr', models.CharField(max_length=254, verbose_name='IP地址')),
                ('username', models.CharField(max_length=254, verbose_name='用户名')),
                ('password', models.CharField(max_length=254, verbose_name='密码')),
                ('port', models.CharField(max_length=254, verbose_name='端口')),
                ('host_type', models.IntegerField(choices=[(0, 'windows'), (1, 'linux')], default=1, verbose_name='系统')),
                ('system_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Hgroup', verbose_name='环境')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
    ]
