# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181030_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hgroup',
            options={'verbose_name_plural': '环境表'},
        ),
        migrations.AlterField(
            model_name='hgroup',
            name='title',
            field=models.CharField(default='10套', max_length=254, unique=True, verbose_name='环境'),
        ),
    ]
