# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181203_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
